### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by ming13** [TheContext/podcaster#1]
# The End Game

## Input

YAML as episodes declaration and Markdown for episode shownotes.

### File Structure
```
├── episodes
│   ├── 11-migration-to-rxjava-2
│   │   ├── episode.yaml
│   │   └── shownotes.md
│   └── 12-instant-apps
│       ├── episode.yaml
│       └── shownotes.md
└── people.yaml
```
* Subdirectories for episode grant some flexibility. Maybe we’ll decide to use different artwork for each episode or something like that.
* Meaningful names instead of just `11` and `12` provide better search and browse experience.

### `episode.yaml`

```yaml
episode:
  number: 10
  title: Kotlin Language Design Nitpicking with Dmitry Jemerov from JetBrains
  hosts:
    - *hannes.dorfmann
    - *artem.zinnatullin
  guests:
    - *dmitry.jemerov
  links:
    - title: Book: Kotlin in Action written by Dmitry Jemerov and Svetlana Isakova
      url: https://www.manning.com/books/kotlin-in-action
    - title: Official Kotlin website with photo of lighthouse on Kotlin island
      url: http://kotlinlang.org/
```

###  `people.yaml`

```yaml
# Not sure about the YAML anchor syntax here.

people:
  - &hannes.dorfmann
    name: Hannes Dorfmann
    twitter: sockeqwe
    blog: http://hannesdorfmann.com
    github: sockeqwe
  - &artem.zinnatullin
    name: Artem Zinnatullin
    twitter: artem_zin
    blog: https://artemzin.com/blog
    github: artem-zinnatullin
```

## RSS

```xml
<item>
	<guid>https://artemzin.com/static/thecontext/episodes/The.Context.episode.11.mp3</guid>
	<title>Episode 11: Migration to RxJava 2 with Artur Dryomov from Juno</title>
	<link>https://github.com/artem-zinnatullin/TheContext-Podcast/blob/master/show_notes/Episode_11.md</link>
	<atom:link rel="replies" type="text/html" href="https://github.com/artem-zinnatullin/TheContext-Podcast/issues/71"/>
	<itunes:duration>52:46</itunes:duration>
	<pubDate>Mon, 15 May 2017 09:30:00 EST</pubDate>
	<enclosure url="https://artemzin.com/static/thecontext/episodes/The.Context.episode.11.mp3" length="50658006" type="audio/mpeg"/>
	
	<atom:contributor>
		<atom:name>Artur Dryomov</atom:name>
		<atom:uri>https://github.com/ming13</atom:uri>
	</atom:contributor>
		
	<itunes:summary>
		<![CDATA[
		
		<h1>Episode 11: Migration to RxJava 2 with Artur Dryomov from Juno</h1>

		<h3><a href="https://github.com/artem-zinnatullin/TheContext-Podcast">How to listen &amp; subscribe</a></h3>

		<ul>
			<li><a href="https://github.com/artem-zinnatullin/TheContext-Podcast/issues/71">Discussion after the episode</a></li>
		</ul>

		<p>We've talked to Artur about Juno's way to migrate their Android Riders App from RxJava 1 to RxJava 2. We have covered:</p>

		<ul>
			<li>Migration strategy at Juno</li>
			<li>What's different in RxJava 2.0?</li>
			<li>Null values in RxJava 2</li>
			<li>Flowable or Observable?</li>
			<li>Other Rx Types: Single, Maybe and Completable</li>
			<li>RxJava 2 interop library</li>
			<li>RxJava 2: Default UncaughtExceptionHandler logs exceptions silently in JVM unit tests</li>
			<li>RxJava 3</li>
		</ul>

		<h4>Guest:</h4>

		<ul>
			<li>Artur Dryomov <a href="https://github.com/ming13">GitHub</a></li>
		</ul>

		<h4>Hosts:</h4>

		<ul>
			<li>Hannes Dorfmann <a href="https://twitter.com/sockeqwe">@sockeqwe</a>, <a href="http://hannesdorfmann.com">personal blog</a>, <a href="https://github.com/sockeqwe">GitHub</a></li>
			<li>Artem Zinnatullin <a href="https://twitter.com/artem_zin">@artem_zin</a>, <a href="http://artemzin.com">personal blog</a>, <a href="https://github.com/artem-zinnatullin">GitHub</a></li>
		</ul>

		<h4>Additional links:</h4>

		<ul>
			<li><a href="https://github.com/gojuno/engineering/blob/master/specs/rxjava-2-migration.md">Juno's Android Rider Team RxJava 2 Migration Specification</a></li>
			<li><a href="https://github.com/ReactiveX/RxKotlin">RxKotlin</a></li>
			<li><a href="https://github.com/akarnokd/RxJava2Interop">RxJava 2 interop library</a></li>
			<li><a href="https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0">What's different in RxJava 2.0</a></li>
			<li><a href="https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0#which-type-to-use">RxJava 2: Which type to use</a></li>
			<li><a href="https://github.com/ReactiveX/RxJava/issues/5234">RxJava 2: Uncaught errors fail silently in junit tests</a></li>
			<li><a href="https://github.com/ReactiveX/RxJava/issues/4644#issuecomment-256684743">RxJava 2: Discussion about null values</a></li>
			<li><a href="https://github.com/reactive-streams/reactive-streams-jvm/issues/204">Reactive Streams specification: null value</a></li>
			<li><a href="https://github.com/ReactiveX/RxKotlin/issues/103">RxJava 2 Kotlin SAM issue combineLatest()/etc</a></li>
			<li><a href="https://github.com/ReactiveX/RxJava/issues/4564">Why RxJava 3: Split the library into two or adding types for symmetry</a></li>
			<li><a href="https://github.com/akarnokd/RxJava3-preview">RxJava 3 Preview</a></li>
		</ul>
		
		]]>
	</itunes:summary>
</item>
```

## Markdown

```markdown
# Episode 11: Migration to RxJava 2 with Artur Dryomov from Juno

### [How to listen & subscribe](https://github.com/artem-zinnatullin/TheContext-Podcast)

 - [Discussion after the episode](https://github.com/artem-zinnatullin/TheContext-Podcast/issues/71)

We've talked to Artur about Juno's way to migrate their Android Riders App from RxJava 1 to RxJava 2. We have covered:

 - Migration strategy at Juno
 - What's different in RxJava 2.0?
 - Null values in RxJava 2
 - Flowable or Observable?
 - Other Rx Types: Single, Maybe and Completable
 - RxJava 2 interop library
 - RxJava 2: Default UncaughtExceptionHandler logs exceptions silently in jvm unit tests
 - RxJava 3

#### Guest:

 - Artur Dryomov [GitHub](https://github.com/ming13)

#### Hosts:

  - Hannes Dorfmann [@sockeqwe](https://twitter.com/sockeqwe), [personal blog](http://hannesdorfmann.com), [GitHub](https://github.com/sockeqwe)
  - Artem Zinnatullin [@artem_zin](https://twitter.com/artem_zin), [personal blog](http://artemzin.com), [GitHub](https://github.com/artem-zinnatullin)

#### Additional links:

  - [Juno's Android Rider Team RxJava 2 Migration Specification](https://github.com/gojuno/engineering/blob/master/specs/rxjava-2-migration.md)
  - [RxKotlin](https://github.com/ReactiveX/RxKotlin)
  - [RxJava 2 interop library](https://github.com/akarnokd/RxJava2Interop)
  - [What's different in RxJava 2.0](https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0)
  - [RxJava 2: Which type to use](https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0#which-type-to-use)
  - [RxJava 2: Uncaught errors fail silently in junit tests](https://github.com/ReactiveX/RxJava/issues/5234)
  - [RxJava 2: Discussion about null values](https://github.com/ReactiveX/RxJava/issues/4644#issuecomment-256684743)
  - [RxJava 2 Kotlin SAM issue combineLatest()/etc](https://github.com/ReactiveX/RxKotlin/issues/103)
  - [Reactive Streams specification: null value](https://github.com/reactive-streams/reactive-streams-jvm/issues/204)
  - [Why RxJava 3: Split the library into two or adding types for symmetry](https://github.com/ReactiveX/RxJava/issues/4564)
  - [RxJava 3 Preview](https://github.com/akarnokd/RxJava3-preview)
```

# The Process

## Validation

Before any generation steps it is possible to run some validations.

```
# podcaster.jar --validate
```

* Check that links actually work.
* Check optional and required fields.

### YAML + Markdown → RSS

Required for various podcast apps.

```
$ podcaster.jar --create-rss
```

* I think it is pretty safe to create Markdown from YAML episode declaration and Markdown shownotes, then render the result as HTML and put to the `<itunes:summary>` section.
* This can be combined with other properties and the resulting RSS can be done.

### YAML + Markdown → Markdown

Required for the Jekyll-based website.

```
$ podcaster.jar --create-markdown
```

Probably will just repeat the `<itunes:summary>` step from RSS generation.

# Workflow

## PR

* After opening a PR to the episodes repository the CI is being invoked.
* Validation is being invoked and fails the build if something is wrong.
* Generation is being invoked and posts resulting Markdown and RSS to the PR as a comment using GitHub API.

## Publishing

* Probably will be invoked manually just as on CI.
* The website repository will store generated Markdown files.
* RSS probably should be posted to a hosting.

**Comment by artem-zinnatullin** [comment]
Can you please give example of episode yml with complex description that uses lists and links? 

You can use some real one https://github.com/artem-zinnatullin/TheContext-Podcast/blob/master/show_notes/Episode_11.md

**Comment by sockeqwe** [comment]
I still like pretty much the idea of having a preview of the (generated) show note (markdown) posted back from CI to github pull request as comment so that reviewer can review rendered markdown.

Therefore podcaster.jar needs to know which files has been changed by the pull request to only post back the preview of the changed files / episode  (travis provide the sha of the commits tgatbhasbchabged by this pull request). Hence, I wouod like to suggest to create only 1 yml file which includes meta data and show notes markdown (not a separte markdown file) because then its easier to determine the changes.

Proposal for episode.yml file

```
episode:
  number: 10
  title: Kotlin Language Design Nitpicking with Dmitry Jemerov from JetBrains
  hosts:
    - *hannes.dorfmann
    - *artem.zinnatullin
  guests:
    - *dmitry.jemerov
  links:
    - title: Book: Kotlin in Action written by Dmitry Jemerov and Svetlana Isakova
      url: https://www.manning.com/books/kotlin-in-action
    - title: Official Kotlin website with photo of lighthouse on Kotlin island
      url: http://kotlinlang.org/

---

Show notes **markdown** section
```
